- docker_swarm:
    state: join
    advertise_addr: "{{ansible_eth0.ipv4.address}}"
    join_token: "{{hostvars[groups['swarm_manager'][0]]['swarm_join_token']}}"
    remote_addrs: ["{{hostvars[groups['swarm_manager'][0]]['ansible_eth0']['ipv4']['address']}}"]

